### ISSUE TITLE
numpy and cython dependencies not installed by pip

### ISSUE THREAD

**Issue by bdon** [drufat/triangle#1]
Hi, thanks for these bindings.

I'm having an issue where i am installing several packages through `pip install -r requirements.txt` and my requirements.txt has numpy, cython and triangle listed. it fails however when triangle's compilation complains that either numpy and cython are not installed; workaround is to first `pip install numpy` and `pip install cython` .

It looks like this has something to do with distutils vs. setuptools, does this sound familiar/on the right track?

**Comment by drufat** [comment]
Fix merged.

**Comment by aespielberg** [comment]
This bug is still happening.  I don't think the fix works.  When I try to build,

Running triangle-2015.12.14/setup.py -q bdist_egg --dist-dir /tmp/easy_install-EjcLcU/triangle-2015.12.14/egg-dist-tmp-6Ynx_G
error: Setup script exited with error: unknown file type '.pxd' (from 'triangle/c_triangle.pxd')

**Comment by drufat** [comment]
Are cython and numpy installed by default on travis? I assumed that since the package installed and the tests worked on a vanilla version of travis the issue was fixed.

**Comment by aespielberg** [comment]
I was able to solve it by installing numpy, and then cython, both with the
--upgrade flag.  This was the only thing that worked for me.  Installing
cython and then numpy did not work.  Installing one and then the other and
then upgrading both did not work.  There seems to be some weird but where
the install order of numpy and cython matters here, but i don't know why.
This might be a cython problem and not a triangle problem; someone should
maybe try looking into it with a fresh install.

**Comment by AngledLuffa** [comment]
I am also having the issue of `unknown file type '.pxd'`, but on MacOS running 10.11 (El Capitan).  I have numpy and cython installed.  As per aespielberg's suggestion, I tried upgrading them, but it still failed to install for me.

**Comment by pdebuyl** [comment]
Hi,

Linux user here. `pip install` complains about `unknown file type '.pxd'` too.

The pxd file should not be listed as a source file, from what I understand. See the discussion here: https://groups.google.com/forum/#!topic/cython-users/Wltkv24JYpY

I can build from source by dropping the `.pxd` file from the `setup.py`. Then, the pxd file disappears from the source dist. It can be added to the package_data, though:

          package_data={'triangle': [
        ...
          'c_triangle.pxd'
      ]},

Should I file a PR?

**Comment by webrot9** [comment]
That doesn't solve the problem for me. I have installed (and upgraded) numpy and cython. I got the unknown file type '.pxd'. Just following the suggestion by pdebuyl it returns the error unknown file type '.pyx'

**Comment by pdebuyl** [comment]
@webrot9 what Python and setuptools version do you have?

    python -V
    python -c 'import setuptools; print setuptools.__version__'

For me: Python 2.7.9 and setuptools 5.5.1

**Comment by webrot9** [comment]
`Python 2.7.6`
setuptools version `19.6`

**Comment by pdebuyl** [comment]
This is strange. I updated setuptools to 19.6 and it still works for me. From the current git master, here is my diff

    --- a/setup.py
    +++ b/setup.py
    @@ -21,7 +21,8 @@ setup(name='triangle',
               'data/*.poly',
               'data/*.area',
               'data/*.edge',
    -          'data/*.neigh'
    +          'data/*.neigh',
    +          'c_triangle.pxd'
           ]},
           version=__version__,
           description='Python binding to the triangle library',
    @@ -49,7 +50,6 @@ setup(name='triangle',
               Extension('triangle.core',
                         [
                             'c/triangle.c',
    -                        'triangle/c_triangle.pxd',
                             'triangle/core.pyx'
                         ],
                         include_dirs=['c'],

**Comment by webrot9** [comment]
Mine is the same... I actually don't know what is wrong.

**Comment by drufat** [comment]
I can't replicate the problem with 

> pip install complains about unknown file type '.pxd' too.

`pip install triangle` works just fine with me. I am going to test on an Apple computer later today to see if I can replicate this bug.

**Comment by drufat** [comment]
pdebuyl, if your changes solve the problem for you, feel free to create a PR and I will merge it if it passes the unit tests.
